spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/neoclue
    username: root
    password: whddhks2
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false

  thymeleaf:
    cache: false

  servlet:
    multipart:            # ✅ spring 아래로 이동
      enabled: true
      max-file-size: 20MB     # 2.2MB 충분히 통과
      max-request-size: 25MB

server:
  error:
    include-message: always
    include-binding-errors: always
  tomcat:
    max-http-form-post-size: 25MB  # ✅ 폼 POST 본문 한도(기본 2MB 근처)
    max-swallow-size: 25MB         # 업로드 중단 시 잔여 바디 처리 한도

logging:
  level:                 # ✅ 깔끔하게 정리
    com.bjw.testtable: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
    com.zaxxer.hikari: INFO

app:
  upload:
    dir: /Users/baekjiwon/uploads
